### ISSUE TITLE
.transition broken in 1.3.0 (working in 1.20)

### ISSUE THREAD

**Issue by chcaru** [d3/d3-selection#164]
This worked in 1.2.0:
`select('.something').transition()`
Now in 1.3.0, it throws:
`select(...).transition is not a function`

I'm assuming it is the d3-selection version bump, but it worked in d3@4.12.2 and now does not in d3@4.13.0

**Comment by mbostock** [comment]
Duplicate of d3/d3#3256. Possible fixes: 1. Upgrade to 5.0. 2. Use the D3 modules directly rather than the `d3` default bundle. 3. Use your package manager, e.g., yarn’s resolutions feature, to pin the versions of the D3 modules so they are consistent with the `d3` package you are using.
